Repository Arman-ali-khan-786/calculator, pull requests merged in 2022-10, with the labels that each got.

#9 Adds contribution guidelines
  CONTRIBUTION.md
Labels: hacktoberfest-accepted

#11 Added Navbar
  index.html
Labels: hacktoberfest-accepted

#13 Updated Readme file with the appropriate information
  README.md
  index.html
Labels: documentation, hacktoberfest-accepted

#19 adjusted the size of the calculator
  index.css
  index.html
Labels: hacktoberfest-accepted

#21 made calculator responsive
  index.css
Labels: hacktoberfest-accepted

#22 Added functionality to buttons
  index.css
  index.html
  index.js
Labels: enhancement, hacktoberfest-accepted

#27 Added Contact page, Favicons, Fixed Navbar Bug, CSS Folder
  contact.html
  css/contact.css
  css/index.css
  favicons/android-chrome-192x192.png
  favicons/android-chrome-512x512.png
  favicons/apple-touch-icon.png
  favicons/favicon-16x16.png
  favicons/favicon-32x32.png
  favicons/favicon.ico
  favicons/site.webmanifest
  index.html
Labels: hacktoberfest-accepted

#30 Added code of conduct and modified contributing guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING_GUIDELINES.md
Labels: documentation, hacktoberfest-accepted

#32 add save previous answer functionality to app
  css/index.css
  index.html
  index.js
Labels: hacktoberfest-accepted
